version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.sedmelluq:lavaplayer
    versions:
    - 1.3.67
    - 1.3.71
