pool:
  vmImage: 'ubuntu-18.04'

trigger:
  batch: true
  branches:
    include:
      - master
jobs:
  - job: Build
    steps:
    - script: sudo apt-get -y update
      displayName: 'Update System Packages'

    - script: sudo apt-get -y install openjdk-11-jdk
      displayName: 'Install Dependencies'

    - script: ./gradlew shadowJar
      displayName: 'Build JAR'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish JAR'
      inputs:
        artifactName: 'cynara-staging'
        PathToPublish: 'build/libs/Cynara-1.0.jar'
