name:
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
          sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
          sudo apt-get install -y software-properties-common
          sudo apt-get install adoptopenjdk-11-hotspot
      - name: Build jar
        run: |
          gradlew shadowJar
  deploy:
    needs: build-jar
    runs-on: ubuntu-latest
    if: github.repository_owner	== 'wpilibsuite'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to Server
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ sercrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "build/libs/bot.jar"
          target: "root"
