name: Build and Deploy
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
          sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
          sudo apt-get install -y software-properties-common
          sudo apt-get install adoptopenjdk-11-hotspot
      - name: Build jar
        run: |
          ./gradlew shadowJar
      - name: Deploy to Server
        if: github.repository_owner == 'daltz333'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "build/libs/bot.jar"
          target: ""
          overwrite: true
          strip_components: 2
      - name: Restart Server
        if: github.repository_owner == 'daltz333'
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo reboot now
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
